### ISSUE TITLE
exportEstimateSaga won't generate estimate's PDF URI

### ISSUE THREAD

**Issue by mnapo** [mezka/presupuestador-react-native#6]
![Issue img](https://user-images.githubusercontent.com/41272015/95122717-4fddff80-0727-11eb-8e44-0a1f740d20c4.jpeg)

**Expected behaviour:** it should download (or at least open in a new window) estimate's PDF generated from server, when pressing "PDF" Button at ViewEditEstimateScreen.

**Comment by mezka** [comment]
Fixed in f34d7c68fe5cc30e90301bbcc0b24b0c2e9d282c
