### ISSUE TITLE
Estimate data isn't loaded into NewEstimateScreen when pressing "Edit" Button at ViewEditEstimateScreen

### ISSUE THREAD

**Issue by mnapo** [mezka/presupuestador-react-native#7]
![Issue image](https://user-images.githubusercontent.com/41272015/95123014-b6fbb400-0727-11eb-942a-5ca9d4e686d4.jpeg)

**Expected behaviour**: load selected estimate data into NewEstimateScreen.

**Comment by mezka** [comment]
Fixed in f34d7c68fe5cc30e90301bbcc0b24b0c2e9d282c, 9d5e4f1c6c0eae444603a69fd2dfcd9efbb71bea, 86ea26837ec59153a4ae2b39caefd7f015537815
